In [1]:
import autokeras as ak
from sklearn.preprocessing import LabelBinarizer
from sklearn.model_selection import train_test_split
import numpy as np
import cv2
import os

In [2]:
classes = os.listdir("animals")
classes

['cats', 'dogs', 'panda']

In [3]:
x=[]
y=[]
for i in classes:
    current_folder = os.path.join("animals",i)
    for j in os.listdir(current_folder):
        image_path = os.path.join("animals",i,j)
        image = cv2.imread(image_path)
        image = cv2.resize(image,(64,64))
        x.append(image)
        y.append(i)

In [4]:
x=np.array(x)/255.0
print(x.shape)
y=np.array(y)
print(y.shape)

(3000, 64, 64, 3)
(3000,)


In [5]:
(trainX, testX, trainY, testY) = train_test_split(x, y, test_size=0.25, random_state=42)

In [6]:
lb = LabelBinarizer()
lb.fit(trainY)
trainY = lb.transform(trainY)
testY = lb.transform(testY)
classes_names = lb.classes_
print(classes_names)
classes_number = len(lb.classes_)
print(classes_number)

['cats' 'dogs' 'panda']
3


In [7]:
clf = ak.ImageClassifier(
    overwrite=True,
    max_trials=1)
clf.fit(trainX, trainY, epochs=100)

Trial 1 Complete [00h 00m 42s]
val_loss: 0.7587279677391052

Best val_loss So Far: 0.7587279677391052
Total elapsed time: 00h 00m 42s
INFO:tensorflow:Oracle triggered exit
Epoch 1/100
71/71 [==============================] - 2s 28ms/step - loss: 0.9422 - accuracy: 0.5582
Epoch 2/100
71/71 [==============================] - 2s 28ms/step - loss: 0.6218 - accuracy: 0.7182
Epoch 3/100
71/71 [==============================] - 2s 28ms/step - loss: 0.4765 - accuracy: 0.8004
Epoch 4/100
71/71 [==============================] - 2s 28ms/step - loss: 0.3388 - accuracy: 0.8693
Epoch 5/100
71/71 [==============================] - 2s 28ms/step - loss: 0.2977 - accuracy: 0.8876
Epoch 6/100
71/71 [==============================] - 2s 28ms/step - loss: 0.2330 - accuracy: 0.9102
Epoch 7/100
71/71 [==============================] - 2s 28ms/step - loss: 0.1579 - accuracy: 0.9436
Epoch 8/100
71/71 [==============================] - 2s 28ms/step - loss: 0.1451 - accuracy: 0.9444
Epoch 9/100
71/71 [=========

71/71 [==============================] - 2s 28ms/step - loss: 0.0147 - accuracy: 0.9947
Epoch 81/100
71/71 [==============================] - 2s 28ms/step - loss: 0.0208 - accuracy: 0.9920
Epoch 82/100
71/71 [==============================] - 2s 32ms/step - loss: 0.0222 - accuracy: 0.9916
Epoch 83/100
71/71 [==============================] - 2s 27ms/step - loss: 0.0359 - accuracy: 0.9893
Epoch 84/100
71/71 [==============================] - 2s 27ms/step - loss: 0.0200 - accuracy: 0.9924
Epoch 85/100
71/71 [==============================] - 2s 27ms/step - loss: 0.0198 - accuracy: 0.9942
Epoch 86/100
71/71 [==============================] - 2s 27ms/step - loss: 0.0191 - accuracy: 0.9938
Epoch 87/100
71/71 [==============================] - 2s 27ms/step - loss: 0.0300 - accuracy: 0.9907
Epoch 88/100
71/71 [==============================] - 2s 27ms/step - loss: 0.0284 - accuracy: 0.9947
Epoch 89/100
71/71 [==============================] - 2s 27ms/step - loss: 0.0132 - accuracy: 0.9956
Epo

In [8]:
predicted_y = clf.predict(testX)
print(predicted_y)

[[9.9703264e-01 2.9659532e-03 1.4408553e-06]
 [1.9990100e-01 8.0009902e-01 4.9124607e-11]
 [3.7749922e-01 6.2250084e-01 9.0806000e-12]
 ...
 [9.3736262e-11 1.7579922e-02 9.8242009e-01]
 [1.1016411e-09 1.0000000e+00 1.3159081e-18]
 [2.2989590e-01 7.7008092e-01 2.3158409e-05]]


In [9]:
print(clf.evaluate(testX, testY))

24/24 [==============================] - 0s 11ms/step - loss: 2.5842 - accuracy: 0.6867
[2.584242105484009, 0.6866666674613953]


In [10]:
from sklearn.metrics import classification_report
print(classification_report(testY.argmax(axis=1), predicted_y.argmax(axis=1), target_names=lb.classes_))

              precision    recall  f1-score   support

        cats       0.67      0.59      0.63       262
        dogs       0.58      0.62      0.60       249
       panda       0.82      0.86      0.84       239

    accuracy                           0.69       750
   macro avg       0.69      0.69      0.69       750
weighted avg       0.69      0.69      0.69       750

